### ISSUE TITLE
Restoring a course with a Medial activity on a Postgres based fresh (meaning empty) Moodle installation crashes

### ISSUE THREAD

**Issue by danowar2k** [streamingltd/moodle-mod_helixmedia#13]
https://github.com/streamingltd/MEDIAL-Moodle-Activity/blob/master/lib.php#L64-L119

This function uses Postgres incompatible SQL when it wants to change the auto increment of table **helixmedia_pre**: https://github.com/streamingltd/MEDIAL-Moodle-Activity/blob/bf39e630379d1a9504219753f988b49498454f20/lib.php#L111C11-L111C11
 
There is no ALTER TABLE AUTO INCREMENT in Postgres. See also https://stackoverflow.com/questions/5342440/reset-auto-increment-counter-in-postgres
 
Please don't use DBMS specific SQL code in the plugin.

**Comment by tim1mw** [comment]
That code dates from 2014 and was put in to deal with a problem reported by a customer using MySQL. Since you're on Postgres, which never had the reported problem, I think the immediate solution here is to only run that code block for MySQL and MariaDB DBMS's .

I've put in a change to fix this on the devfixes branch in commit https://github.com/streamingltd/MEDIAL-Moodle-Activity/commit/29bdb614b515efb31acd6fe968a284331815d6bd . I'll roll that into the next full plugin release as well.

**Comment by danowar2k** [comment]
Thanks!

**Comment by danowar2k** [comment]
Looks like the fix hasn't arrived in master yet, or has it?

**Comment by tim1mw** [comment]
Hmm... it should have been in master, but clearly isn't there. I think it got lost somehow from our underlying dev version. I've put the fix back in so it should finally make it to master in the next release.

**Comment by tim1mw** [comment]
Now fixed in https://github.com/streamingltd/moodle-mod_helixmedia/commit/15e0c78267dd9b329607e77db7f756f480505d58
